Address minor items flagged by PVS Studio in 0.8.1
Cyan4973/xxHash pull request #628
Opened 2021-11-30 18:55 UTC by kcgen

- Fixes #625
 - Fixes #626
 - Fixes #627 

After this PR, PVS Studio [no longer flags any issues in xxHash.](https://github.com/dosbox-staging/dosbox-staging/runs/4371841895?check_suite_focus=true)

This PR was tested in DOSBox Staging and the hashed output diffed with prior runs (and were identical).

2021-11-30 18:59 UTC, Cyan4973 requested changes
Only the second issue `nbStripesToEnd` is fine in this PR.

I'll proceed differently for the other 2 issues.

2021-11-30 19:06 UTC, kcgen commented
> Only the second issue `nbStripesToEnd` is fine in this PR.
> 
> I'll proceed differently for the other 2 issues.

Thanks for addressing these @Cyan4973.  Happy to re-run more PVS scans to help wrap these up.

2021-11-30 19:27 UTC, kcgen commented
> I'll proceed differently for the other 2 issues.

Dropped the other two commits.

2021-12-01 01:46 UTC, Cyan4973 approved these changes

2021-12-01 01:46 UTC, merged